on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - uses: actions/checkout@v3
      - id: foo
        uses: rock-paper-scissors/actions/shared/action.yml@main
        with:
          who-to-greet: 'Mona the Octocat'
          script-to-run: 'bye.sh'
      - run: echo random-number ${{ steps.foo.outputs.random-number }}
        shell: bash
